<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="bogon" ignored="0" name="Mocks" tests="5" failures="1" timestamp="22 十一月 2017 02:31:16 GMT" time="0.558" errors="0">
  <testcase name="addPersonToEmployeeDirectory" time="0.011" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
  <testcase name="checkFirstNameFunction" time="0.489" classname="org.quickstart.testng.samples.EmployeeDirectoryTest">
    <failure type="org.mockito.exceptions.verification.TooManyActualInvocations" message="
iPerson.getFullName();
Wanted 1 time:
-&amp;gt; at org.quickstart.testng.samples.EmployeeDirectoryTest.checkFirstNameFunction(EmployeeDirectoryTest.java:63)
But was 2 times. Undesired invocation:
-&amp;gt; at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
">
      <![CDATA[org.mockito.exceptions.verification.TooManyActualInvocations: 
iPerson.getFullName();
Wanted 1 time:
-> at org.quickstart.testng.samples.EmployeeDirectoryTest.checkFirstNameFunction(EmployeeDirectoryTest.java:63)
But was 2 times. Undesired invocation:
-> at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

	at org.quickstart.testng.samples.EmployeeDirectoryTest.checkFirstNameFunction(EmployeeDirectoryTest.java:63)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- checkFirstNameFunction -->
  <testcase name="checkFirstNameFunctionInvocation" time="0.003" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
  <testcase name="checkFirstPersonNameInTheDirectory" time="0.026" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
  <testcase name="shouldThrowExceptionWhenAccessingFirstPersonOnEmptyDirectory" time="0.001" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
</testsuite> <!-- Mocks -->
